name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - macOS 12 (Monterey)
        - macOS 13 (Ventura)
        - macOS 14 (Sonoma)
        - macOS 15 (Sequoia)
        - Windows 10
        - Windows 11
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "e.g., 3.10.0, 3.11.5, 3.12.0"
    validations:
      required: true

  - type: input
    id: repoqa-version
    attributes:
      label: RepoQA Version
      description: What version of RepoQA are you using?
      placeholder: "e.g., 1.0.0, main branch, commit hash"
    validations:
      required: true

  - type: dropdown
    id: virtual-environment
    attributes:
      label: Virtual Environment
      description: Are you using a virtual environment?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - Error messages or logs
        - Screenshots if applicable
        - Any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true