name: Feature Request
description: Suggest a new feature for RepoQA
title: ""
labels: ["story", "task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: A brief, descriptive title for your feature request
      placeholder: "e.g., Add support for GitLab repositories"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like to see?
      description: A clear, concise description of the feature you'd like added.
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    id: problem-solved
    attributes:
      label: Why do you need this feature?
      description: Explain the problem this feature would solve or the value it would add.
      placeholder: What problem does this solve? What value would it add?
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Describe how you envision the feature working from a user's perspective.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: examples-mockups
    attributes:
      label: Examples or Mockups
      description: If applicable, add screenshots, code examples, or mockups.
      placeholder: Add any examples, code snippets, or mockups that help illustrate your request...
    validations:
      required: false

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Technical Features (AI models, performance, APIs)
        - User Experience Features (UI/UX, documentation)
        - Integration Features (new services, cloud providers)
        - Other
    validations:
      required: true

  - type: dropdown
    id: implementation-interest
    attributes:
      label: Implementation Interest
      description: Are you interested in implementing this feature yourself?
      options:
        - "Yes, I'd like to implement this"
        - "Maybe, depending on complexity"
        - "No, I'm just suggesting the idea"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or references related to this feature request.
      placeholder: |
        - Links to related issues or discussions
        - References to similar features in other tools
        - Any other relevant context
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have reviewed the project roadmap to see if this is already planned
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true